### ISSUE TITLE
support php 7

### ISSUE THREAD

**Issue by aretecode** [phpflo/phpflo#24]
- php 5 is EOL, php 7 is current
- add note in readme for version to use if still migrating from php 5

**Comment by maschmann** [comment]
I suggest setting the minimum version dependency to 7 with the next minor version bump, since semver allows for php version changes within minor version changes.
Also the composer requirement will state during install, which version of php is required and previous installations won't automatically update, even if they use the "death star" versioning ("*") constraint.
Also "require phpflo/phpflo" will automatically install the correct version for the user's environment.

What do you think about php 7 migration _after_ the next featureset with flowtrace etc.?
Then I'll do a re-work on all five repos.

Thereafter I'm still thinking about moving from evenement to something else (league/event ;-)), although this will break a lot of things.
With php 7, Component trait maybe, too :-)
