### ISSUE TITLE
Test coverage is too low to consider phpflo as a dependency

### ISSUE THREAD

**Issue by tigitz** [phpflo/phpflo#31]
While considering phpflo as the backbone of a project of mine (A Markdown/PHP Spellchecker CI Tool) I stumbled upon two trivial bugs while using the most basic feature. I took the time to fix them and happily contribute.

However I would like to state that it made me rethink about making phpflo a critical part of my application, giving the low test coverage. And that's a shame because one of the main motivation of open-sourcing is to help people do cool things with it or build better things on top of it.

But I'm far from being sure it would help me to do that in this state.

I would suggest focusing on tests for the next milestones, it would also probably help you to detect hidden dependencies. Everything you're building right now, you're probably building on top of something not tested and it will be a pain in the a** when you'll thought about refactoring because later stage testing make you realise something is wrong within your architecture.

I might give a hand too as long as it's a project's real determination to improve tests.

Cheers

**Comment by maschmann** [comment]
Hi @tigitz,
first: Thank you for contributing :+1: 
As of now I am working on a [branch/PR ](https://github.com/maschmann/phpflo/tree/feature/test_improvements) for higher test coverage, since I am using this as the base for several ETL processes in production.
The previous goals were to add needed functionality concerning the mentioned ETL processes, gradually refactoring to PHP 7 compatibility, fixing some state related problems while using the lib with symfony and now stability.
Since this is done in my spare time, I'm sadly not that fast, so every help is absolutely welcome :-)

Regards

**Comment by tigitz** [comment]
Oh, too bad I didn't see your PR first, great to know ! But now I'm confused, how should we do to not overlap each other if you work on your own fork ? Wouldnt it be better to have the branch on the main repo ?

I fully understand your position and I will gladly give some help to reach the desired package state.

**Comment by maschmann** [comment]
Sounds great! :+1: 
Forking/PRing is the standard in github, so I'd suggest staying with it. We can do the testing stuff class-based. That's the usual way I'm working on tests when not tdd'ing ;-)
So: PR per class?

**Comment by tigitz** [comment]
Fine by me, I'm just wondering how I can work on a PR you submitted. I think I'll make a PR based on yours and wait till yours is merged so that the "changes" part of mine doesnt involve yours.

I could also make comments on yours, but most of the time it's faster writing code than comment.

Let me know the prefered workflow.
