### ISSUE TITLE
question

### ISSUE THREAD

**Issue by qooco** [phpflo/phpflo#39]
Could you gime more examples on php, some interesting and complex

**Comment by qooco** [comment]
What if I need extra data (on other InPorts) - and work with all data throught one method (process)
It data come from different components

**Comment by maschmann** [comment]
Hi @qooco,
sorry for taking so long to respond. I'm using this for e.g. ETL processes where I put in a product from a MySQL query in form of an array which later leads to a MongoDB document which is then persisted.
I can't give you code to view, since it's code from a recent client's project.
Another complex thing I did was a (generic) rss generator:
![flow](https://github.com/Motorpresse/diagrams/raw/master/flow-rss-feed-generator.png)

**Comment by qooco** [comment]
Hi, thanks for answer, I was thinking that the project was was abandoned.

Another question: phpflo/phpflo-component it is all or exists another reusable components ? I would like to know, becouse I would like to try phpflo sometime. (in some real projects)

also is interesting the https://github.com/phpflo/phpflo/issues/14 (process API, runtime for working with flowhub). noflo style. I understand that it requires time, so it is only pure interest

**Comment by maschmann** [comment]
Yes, there aren't that many components yet :-(
The project is not abandoned: I've already built a refactoring branch a few month ago which has to be re-integrated into the main repository. Time is the problem -.-

I've not yet integrated any flowhub integration, yet. Don't know when I might get around to that.

**Comment by maschmann** [comment]
I think all questions are answered :-)
